name: firedpy
channels:
  - conda-forge
dependencies:
  - beautifulsoup4
  - dask
  - descartes
  - gdal
  - geopandas
  - lxml
  - matplotlib
  - netcdf4 # This may need to be built from file with a conifg set to point to HDF5 headers for linux distros
  - numpy
  - pandas
  - pyyaml
  - rasterio
  - scipy
  - tabula-py
  - toolz
  - tqdm
  - xarray==0.11.3
