name: firedpy
channels:
  - defaults
dependencies:
  - beautifulsoup4
  - dask
  - descartes
  - gdal
  - geopandas
  - fiona
  - lxml
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pycurl
  - pyyaml
  - rasterio
  - requests
  - toolz
  - tqdm
  - xarray
